Fix memory leaking tests.
Fantom-foundation/Carmen pull request #1031
Opened 2024-09-20 12:18 UTC by cabrador

This PR closes bunch of `StateDbs` which caused memory leaks.

2024-09-21 16:14 UTC, HerbertJordan requested changes
Thanks for cleaning up the `state` package tests. 

While I appreciate the effort, I think that in particular for the `StateDB` tests (`state_db_test.go`) that are all based on mocks of the underlying state DB, the extra boiler plate code is not warranted. It  adds extra clutter distracting from the core operations under test. Unless this is fixing an actual resource issue, I would favor the previous code.

Have you identified the memory issues using heap-dumps like in the MPT package? Is this PR eliminating all of them, or is more work required in the `state` package?

2024-09-21 16:14 UTC, HerbertJordan commented on go/state/state_db_test.go
All tests in this file target the `StateDB` instance that manages transaction scopes and sits between the VM and the actual database. To be database-independent, all those tests use (deliberately) a mocked version of a database, that can not leak memory or resources. Thus, I think it is unnecessary clutter to add close calls to all those mock-based `StateDB` instances, which just leads to the need of additional `Flush` and `Close` expectations.

Unless there is evidence that the previous version actually caused resource issues, I would argue that this is adding complexity and clutter that should be avoided.

2024-09-23 06:22 UTC, kjezek requested changes
I would give about the same feedback as @HerbertJordan 
I do not see how this PR can "fix memory leaking tests"?

I did some measurement, and it shows that majority of memory is consumed by` LruCache` used in schemas 1-3. I.e. it seems that this memory is not released when closing a state. This should be targeted mainly. 

![pprof002](https://github.com/user-attachments/assets/99719550-e304-4a14-80dc-96f59c28c244)

2024-09-24 08:20 UTC, kjezek submitted a review, later dismissed
Thanks for fixing this. Can you give an example why `Flush` was failing?

Also I wonder if this change fixes all leaks related to `LruCache`.  Most notably, the chart I provided, and the chart you provided, look quite different. In particular, in my chart, there leaked 9GB and was many more `LruCache` instances, from many more tests.

2024-09-24 08:20 UTC, kjezek commented on go/state/state_db.go
> +
this change is unrelated, please revert.

I understand that it was done by IDE, and for this reason we accept such changes when there are real functional changes in the file. But in this case nothing has changed

2024-09-24 08:20 UTC, kjezek commented on go/state/state_db_and_state_test.go
> +			defer func() {
this update changes nothing

2024-09-24 15:39 UTC, cabrador commented
Moved to #1034

2024-09-24 15:39 UTC, closed without merging