Fix multiple flushing of codes
Fantom-foundation/Carmen pull request #836
Opened 2024-04-23 05:26 UTC by hkalina

Everytime when MptState is being Flushed, the codes file is written to the disk, even when no code have been modified.

This affects event the time of Carmen closing, as the flush is called here several times:

![image](https://github.com/Fantom-foundation/Carmen/assets/3178122/d226d1f6-e85f-47e5-a1c5-600f6bdf18d8)

This PR adds a codeDirty flag, which avoids these unnecessary overrides.

2024-04-23 06:15 UTC, HerbertJordan requested changes
Thanks for adding this, looks good to me, but I can only approve this with proper unit test coverage.

At the least, there needs to be a test that tests that after this change indeed codes are only flushed once.

2024-04-23 06:15 UTC, HerbertJordan commented on go/database/mpt/state.go
There is also a `GetCodes` function that should be replaced by
```
func (s *MptState) GetCodes() (map[common.Hash][]byte, error) {
	s.codeMutex.Lock()
	res := maps.Clone(s.code)
	s.codeMutex.Unlock()
	return res, nil
}
```

2024-04-23 06:30 UTC, hkalina commented on go/database/mpt/state.go
Are you sure? This may significantly slow-down the genesis export, which seems to be the only usage of this.
Would not be a comment warning that the provided map must not be accessed concurrently with the state writes sufficient?

2024-04-23 09:19 UTC, HerbertJordan commented on go/database/mpt/state.go
I do not think this has a high impact on the export time. The codes are not a huge contributor to the overall runtime. Also, the clone operation is a shallow-clone, only copying the map structure but not the codes in it.

2024-04-24 06:49 UTC, HerbertJordan requested changes
Looks good, just one small additional test-step request.

2024-04-24 06:49 UTC, HerbertJordan commented on go/database/mpt/state_test.go
> +}
Can you add a third flush after an actual modification to include coverage for the "mark-dirty" mechanism?

2024-04-25 06:27 UTC, HerbertJordan approved these changes
Thanks!

2024-05-03 15:05 UTC, merged