Has empty storage
Fantom-foundation/Carmen pull request #897
Opened 2024-06-09 08:36 UTC by petr-hanzl

This PR adds `HasEmptyStorage(addr)` which returns true if given address has empty storage.

2024-06-10 13:32 UTC, kjezek requested changes
this PR is quite big. Could you split it into a PR for the LiveDB and ArchiveDB?

For the issue this PR resolves, it needs only the LiveDB, i.e. the ArchiveDB has a minor priority at the moment, if ever needed at all.

2024-06-10 14:38 UTC, HerbertJordan commented
> this PR is quite big. Could you split it into a PR for the LiveDB and ArchiveDB?

I agree, it needs to be cut down a bit. Maybe even an initial PR just with the changes targeting the `Forest`, followed by the `LiveDB` and then all the way up to the `Carmen` API.

2024-06-10 14:41 UTC, HerbertJordan commented on go/database/mpt/nodes.go
> +	return n.storage.Id().IsEmpty(), nil
At this point you may have reached the wrong `AccountNode`. Without checking the address, you would not know.

For instance, if you create a MPT with a single account with address `A` and then add a single storage slot, and then ask whether account `B` (A!=B) has an empty storage, the answer probably is no, although `B` should have an empty storage.

2024-06-10 14:42 UTC, petr-hanzl commented
> this PR is quite big. Could you split it into a PR for the LiveDB and ArchiveDB?
> 
> For the issue this PR resolves, it needs only the LiveDB, i.e. the ArchiveDB has a minor priority at the moment, if ever needed at all.

I dont think we can split it between Live and Archive. I need to extend [this](https://github.com/Fantom-foundation/Carmen/blob/54a30889e0311491d62d88d08a965e91f91be69d/go/state/state.go#L25) interface which is implemented by ArchiveState. I will create PR with just the `Mpt`/`Forest`/`LiveTrie` implementation but the rest will need to be done altogether.

2024-06-10 15:30 UTC, kjezek commented
> > this PR is quite big. Could you split it into a PR for the LiveDB and ArchiveDB?
> > For the issue this PR resolves, it needs only the LiveDB, i.e. the ArchiveDB has a minor priority at the moment, if ever needed at all.
> 
> I dont think we can split it between Live and Archive. I need to extend [this](https://github.com/Fantom-foundation/Carmen/blob/54a30889e0311491d62d88d08a965e91f91be69d/go/state/state.go#L25) interface which is implemented by ArchiveState. I will create PR with just the `Mpt`/`Forest`/`LiveTrie` implementation but the rest will need to be done altogether.

Right, thanks for explanation. I think we can keep the method in Archive unimplemented until it is finished.  Or as Herbert recommended, build bottom up all components and then only connect them from the top. But the liveDb has priority to fix #887

2024-06-11 07:07 UTC, petr-hanzl commented
This PR will be split into multiple smaller ones.

2024-06-11 07:07 UTC, closed without merging